export const RSERVATION_TYPE = {
  SET_SEAT_DATA: "SET_SEAT_DATA",
  DELETE_SEAT_DATA: "DELETE_SEAT_DATA",
  SET_USER_DATA: "SET_USER_DATA",
  DELETE_USER_DATA: "DELETE_USER_DATA",
  UPDATE_USER_DATA: "UPDATE_USER_DATA",
  SET_NAVIGATION: "SET_NAVIGATION",
};
