export const seatArray = [
  {
    lowerDesk: [
      { seatNumber: "L1", desk: "Lower", category: "double", booked: false },
      { seatNumber: "L2", desk: "Lower", category: "double", booked: false },
      { seatNumber: "L3", desk: "Lower", category: "single", booked: false },
      { seatNumber: "L4", desk: "Lower", category: "single", booked: false },
      { seatNumber: "L6", desk: "Lower", category: "double", booked: false },
      { seatNumber: "L5", desk: "Lower", category: "double", booked: false },
      { seatNumber: "L7", desk: "Lower", category: "double", booked: false },
      { seatNumber: "L8", desk: "Lower", category: "double", booked: false },
      { seatNumber: "L9", desk: "Lower", category: "single", booked: false },
      { seatNumber: "L10", desk: "Lower", category: "single", booked: false },
      { seatNumber: "Ll2", desk: "Lower", category: "double", booked: false },
      { seatNumber: "Ll1", desk: "Lower", category: "double", booked: false },
      { seatNumber: "Ll3", desk: "Lower", category: "double", booked: false },
      { seatNumber: "Ll4", desk: "Lower", category: "double", booked: false },
      { seatNumber: "Ll5", desk: "Lower", category: "single", booked: false },
      { seatNumber: "Ll6", desk: "Lower", category: "double", booked: false },
      { seatNumber: "Ll7", desk: "Lower", category: "double", booked: false },
      { seatNumber: "Ll8", desk: "Lower", category: "single", booked: false },
    ],
    upperDesk: [
      { seatNumber: "U1", desk: "Upper", category: "double", booked: false },
      { seatNumber: "U2", desk: "Upper", category: "double", booked: false },
      { seatNumber: "U3", desk: "Upper", category: "single", booked: false },
      { seatNumber: "U4", desk: "Upper", category: "single", booked: false },
      { seatNumber: "U6", desk: "Upper", category: "double", booked: false },
      { seatNumber: "U5", desk: "Upper", category: "double", booked: false },
      { seatNumber: "U7", desk: "Upper", category: "double", booked: false },
      { seatNumber: "U8", desk: "Upper", category: "double", booked: false },
      { seatNumber: "U9", desk: "Upper", category: "single", booked: false },
      { seatNumber: "U10", desk: "Upper", category: "single", booked: false },
      { seatNumber: "Ul2", desk: "Upper", category: "double", booked: false },
      { seatNumber: "Ul1", desk: "Upper", category: "double", booked: false },
      { seatNumber: "Ul3", desk: "Upper", category: "double", booked: false },
      { seatNumber: "Ul4", desk: "Upper", category: "double", booked: false },
      { seatNumber: "Ul5", desk: "Upper", category: "single", booked: false },
      { seatNumber: "Ul6", desk: "Upper", category: "double", booked: false },
      { seatNumber: "Ul7", desk: "Upper", category: "double", booked: false },
      { seatNumber: "Ul8", desk: "Upper", category: "single", booked: false },
    ],
  },
];
// export const singleSeatNumbers = ["L3", "L4", "L9", "L10"];
